import { useCallback, useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { HiHeart, HiOutlineArrowUpTray, HiOutlineChatBubbleOvalLeft, HiOutlineHeart, HiOutlinePlus, HiOutlineSpeakerWave, HiOutlineSpeakerXMark } from 'react-icons/hi2';
import api from '../api/client';
import CommunityShell from '../features/community/components/CommunityShell';

function Reel({ post, active }) {
    const videoRef = useRef(null); const [liked, setLiked] = useState(post.liked); const [muted, setMuted] = useState(true);
    const media = post.media?.find((item) => item.kind === 'video');
    useEffect(() => { if (!videoRef.current) return; if (active) videoRef.current.play().catch(() => {}); else videoRef.current.pause(); }, [active]);
    const like = async () => { const next = !liked; setLiked(next); try { if (next) await api.post(`/posts/${post.id}/like`); else await api.delete(`/posts/${post.id}/like`); } catch { setLiked(!next); } };
    if (!media) return null;
    return <article className="relative h-[calc(100vh-8rem)] min-h-[620px] snap-start overflow-hidden rounded-2xl bg-black shadow-xl"><video ref={videoRef} src={media.variants?.web?.url || media.url} poster={media.variants?.poster?.url} loop playsInline muted={muted} preload="metadata" className="h-full w-full object-contain" onClick={() => videoRef.current?.paused ? videoRef.current.play() : videoRef.current?.pause()} /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/20" /><div className="absolute inset-x-0 bottom-0 p-5 pe-20 text-white"><p className="font-bold">{post.acting_as?.type === 'organization' ? post.acting_as.name : post.author?.name}</p><div className="mt-2 line-clamp-3 text-sm text-white/90" dangerouslySetInnerHTML={{ __html: post.body }} />{post.product ? <Link to={`/products/${post.product.id}`} className="mt-3 inline-flex rounded-lg bg-white/15 px-3 py-2 text-xs font-bold backdrop-blur">عرض المنتج: {post.product.name}</Link> : null}</div><div className="absolute bottom-5 end-3 flex flex-col gap-3"><button onClick={like} className="flex h-12 w-12 items-center justify-center rounded-full bg-black/45 text-white backdrop-blur">{liked ? <HiHeart className="h-6 w-6 text-red-500" /> : <HiOutlineHeart className="h-6 w-6" />}</button><Link to={`/community/post/${post.id}`} className="flex h-12 w-12 items-center justify-center rounded-full bg-black/45 text-white backdrop-blur"><HiOutlineChatBubbleOvalLeft className="h-6 w-6" /></Link><button onClick={() => navigator.share?.({ url: `${location.origin}/community/post/${post.id}` })} className="flex h-12 w-12 items-center justify-center rounded-full bg-black/45 text-white backdrop-blur"><HiOutlineArrowUpTray className="h-6 w-6" /></button><button onClick={() => setMuted((value) => !value)} className="flex h-12 w-12 items-center justify-center rounded-full bg-black/45 text-white backdrop-blur">{muted ? <HiOutlineSpeakerXMark className="h-6 w-6" /> : <HiOutlineSpeakerWave className="h-6 w-6" />}</button></div></article>;
}

export default function ReelsPage() {
    const [posts, setPosts] = useState([]); const [cursor, setCursor] = useState(null); const [active, setActive] = useState(0); const loading = useRef(false);
    const load = useCallback(async () => { if (loading.current) return; loading.current = true; try { const { data } = await api.get('/reels', { params: cursor ? { cursor } : {} }); setPosts((old) => [...old, ...(data.data || [])]); setCursor(data.meta?.next_cursor || null); } finally { loading.current = false; } }, [cursor]);
    useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
    const onScroll = (event) => { const element = event.currentTarget; const index = Math.round(element.scrollTop / Math.max(1, element.clientHeight)); setActive(index); if (index >= posts.length - 2 && cursor) load(); };
    return <CommunityShell rightRail={false}><div className="relative"><div onScroll={onScroll} className="h-[calc(100vh-7rem)] snap-y snap-mandatory space-y-4 overflow-y-auto rounded-2xl">{posts.map((post, index) => <Reel key={post.id} post={post} active={index === active} />)}{posts.length === 0 ? <div className="flex h-full items-center justify-center rounded-2xl bg-slate-950 text-slate-300">لا توجد Reels بعد</div> : null}</div><Link to="/community/create?format=reel" className="absolute end-4 top-4 z-10 flex items-center gap-2 rounded-full bg-blue-600 px-4 py-2 text-sm font-bold text-white shadow-lg"><HiOutlinePlus className="h-5 w-5" />إنشاء Reel</Link></div></CommunityShell>;
}
